import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../style/Home.module.css'
import {formatPrice} from '../components/FormatPrice'
import {AllSearch} from '../components/AllSearch'
import {Filters} from '../components/Filters'

const defaultEndPoint = 'https://gateway.marvel.com:443/v1/public/comics?ts=1&apikey=717174d03db4fafc2db6e81ab37e5a20&hash=464cfe846f37a492d924ef2df3167ad2';


export async function getServerSideProps() {
  const res = await fetch (defaultEndPoint);
  const data = await res.json()
  return { props: { data } }
}

export default function Home({ data }) {
  const { results = [] } = data.data;
  const [searchValue, setSearchValue] = useState('');
  
  let searchedComics = [];

  if (!searchValue.length >= 1) {
    searchedComics = results;
  } else {
      searchedComics = results.filter(comic => {
      const comicText = comic.title.toLowerCase();
      const searchText = searchValue.toLowerCase();
      return comicText.includes(searchText);
    });
  }
 
  return (
    <>
      <Head>
        <title>Marvel API</title>
        <meta name="description" content="Generated by Marvel API" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <img className={styles.img} src="/Marvel_Logo.png" alt="Marvel Logo" /> 
      </header>

      <section className={styles.filters}>
        <AllSearch
            searchValue = {searchValue}
            setSearchValue = {setSearchValue}
        />
        <Filters
            searchValue={searchValue}
            setSearchValue = {setSearchValue}
        />
      </section>

      <main className={styles.main}>



        <ul className={styles.grid}>
          {searchedComics.map (result => {
            const { id, title, thumbnail, creators, prices} = result;
            const cover = thumbnail.path+"."+thumbnail.extension;
            const price = formatPrice(prices[0].price);
            const creator = creators.items;
            

            return (
              <li key={id} className={styles.card}>
                <div className={styles.containerimg} >
                  <img src={cover} alt={title} className={styles.coverimage}></img>
                </div>
                <h2>{title}</h2>
              

                {creator.map (writer => {
                  const {name, role} = writer;
                  if (role === 'writer') {
                    return <p>{name}</p>
                  }
                })} 

                 <button>{price}</button>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <p>Powered by{' '}</p>
        <a
            href="https://ricardomazuera.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            Ricardo Mazuera
          </a>
      </footer>
    </>
  )
}