export const TYPE = {
    SET_DATA: "SET_DATA",
    SET_DATA_FILTER: "SET_DATA_FILTER",
    SET_CURRENT_FILTER: "SET_CURRENT_FILTER",
    SET_USER_DATA_RESULT: "SET_USER_DATA_RESULT",
    SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
}

export const COMICS_COUNT = 20;

export const STATUS_CODE = {
    OK: 200,
    ERROR_MISSIN: 409,
    INVALID_PARAMETER: 401,
    NO_ALLOWED: 405,
    FORBIDDEN: 403
}