import Head from "next/head";
import { useState } from "react";
import styles from "../style/Home.module.css";
import { AllSearch } from "../components/AllSearch";
import { Filters } from "../components/Filters";
import { Header } from "../components/Header";
import { Cards } from "../components/Cards";
import { Footer } from "../components/Footer";
import { apiFetch } from "../helpers/apiFetch";

export async function getServerSideProps() {
  let data = await apiFetch();
  return { props: { data } };
}

export default function Home({ data }) {
  const { results = [] } = data.data;
  const [searchValue, setSearchValue] = useState("");

  return (
    <>
      <Head>
        <title>Marvel API</title>
        <meta name="description" content="Generated by Ricardo Mazuera" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section className={styles.filters}>
        <AllSearch searchValue={searchValue} setSearchValue={setSearchValue} />
        <Filters searchValue={searchValue} setSearchValue={setSearchValue} />
      </section>

      <Cards results={results} searchValue={searchValue} />

      <Footer />
    </>
  );
}
